# base image
FROM node:alpine as react-build

# set working directory
RUN mkdir /app
WORKDIR /app

COPY package.json .
RUN npm install
RUN npm install react-scripts -g

COPY . .

ENV PATH /app/node_modules/.bin:$PATH

RUN npm run build

###### BUILD
FROM nginx
COPY --from=react-build /app/build /usr/share/nginx/html