version: "3.7"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_NAME=hellodev
    ports:
      - 3001:3000
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
