# base image
FROM node:alpine

# set working directory
RUN mkdir /app
WORKDIR /app

COPY package.json .
RUN npm install
RUN npm install react-scripts -g

COPY . .

ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 3000
# start app
CMD ["npm", "start"]